### PR TITLE
Changes to compile in Allegro w/mlisp

### PR DESCRIPTION
**Pull request by franzinc**
Only changes are to downcase symbol and package names.

In a couple of cases, downcase regions of code in all uppercase. In
both cases, the surrounding code was in lowercase.

### CODE REVIEW

**Comment by franzinc** [comment]
How does http://mmaul.github.io/clml/ get updated?  The `README.md` of this repo has a fix that doesn't.  Specifically, this line:
`CL-USER (setf *syobu* (hjs.learn.read-data:read-data-from-file `
has been updated in the clml repo to use the correct package.

**Comment by mmaul** [comment]
Regarding how http://mmaul.github.io/clml/ gets updated. It is currently manual, following proc described in 'Building Documentation' in the manual (and then committing and pushing to the github.io repo). It could be automated easily enough using a doc build server, or just implementing a git hook to do it on commit of changes to .org files. In this particular case I was just lazy and chucked the fix in the README.md instead of putting it in README.org.

**Comment by mmaul** [comment]
Alot of the upcasing was in the generated code from f2cl for the translation of BLAS, the rest from yanking text from the REPL. Thanks for the fixes though, and I will rebuild the docs.

**Comment by mmaul** [comment]
Ah modern mode, didn't think about that. A while back I had got an eval licence of Allego  to get clml working on Allegro, but I apparently was not aware of modern mode.

**Comment by franzinc** [comment]
No problem.  Thanks for merging this so quickly!

**Pull request merged**
